In [2]:
# Import tensorflow library
import tensorflow as tf

In [6]:
# Starts with a session
sess = tf.Session()

# Build a calculation graph
node1 = tf.constant([1.0, 1.0, 1.0])
node2 = tf.constant([2.0, 2.0, 2.0])
adder = tf.add(node1, node2)

# Evaluate result : Running through the graph and run each nodes (operations).
# It is important that the actual computation of the graph take place in here.
result = adder.eval(session=sess)

print(result)

sess.close()

[3. 3. 3.]


In [10]:
# Another simple example using with and overloading
with tf.Session():
    # Shape: shape of the tensor. in this case, each tensor has 4 items and 1 dimension.
    node1 = tf.constant(1.0, shape=[4])
    node2 = tf.constant(2.0, shape=[4])
    node3 = tf.constant(3.0, shape=[4])
    adder = node1 + node2 + node3
    
    print(adder.eval())

[6. 6. 6. 6.]


In [19]:
import numpy as np

# Adding matrices is as simple as adding vectors
with tf.Session():
    node1 = tf.constant(1.0, shape=[2, 3])
    
    # np.arange make a serial data in range.
    simple = np.arange(1.0, 7.0, dtype=np.float32)
    print(simple)
    
    node2 = tf.constant(np.reshape(simple, (2, 3)))
    adder = node1 + node2
    
    print(adder.eval())

[1. 2. 3. 4. 5. 6.]
[[2. 3. 4.]
 [5. 6. 7.]]


In [21]:
import tensorflow as tf
import numpy as np

# Multiplcation of Matrices..
with tf.Session():
    input_features = tf.constant(np.reshape([1, 0, 0, 1], (1, 4)).astype(np.float32))
    weights = tf.constant(np.random.randn(4, 2).astype(np.float32))
    output = tf.matmul(input_features, weights)
    print("Input:")
    print(input_features.eval())
    print("Weights:")
    print(weights.eval())
    print("Output:")
    print(output.eval())

Input:
[[1. 0. 0. 1.]]
Weights:
[[ 1.4764901   1.9907105 ]
 [-0.5350998  -0.7286895 ]
 [-0.19299382  0.73151696]
 [ 0.9400458   0.3905921 ]]
Output:
[[2.4165359 2.3813026]]


#### Use of tf.Variable, tf.assign

In [47]:
import tensorflow as tf
import numpy as np

with tf.Session() as sess:
    total = tf.Variable(tf.zeros([2, 2]))
    random_values = tf.Variable(tf.random_uniform([2, 2], maxval=10))
    tf.global_variables_initializer().run()
    
    update_total = tf.assign(total, tf.add(total, random_values))
    update_random_values = tf.assign(random_values, tf.random_uniform([2, 2], maxval=10))
    
    for i in range(10):
        sess.run(update_total)
        sess.run(update_random_values)
        print(total.eval())

[[3.689779   7.236499  ]
 [2.6037264  0.54228306]]
[[10.956362  8.680584]
 [10.206676  2.88077 ]]
[[15.549495 11.088782]
 [18.862587  7.382964]]
[[21.37453  16.685987]
 [25.577042 16.811672]]
[[24.372948 21.60711 ]
 [28.95485  25.907555]]
[[32.785454 24.338793]
 [37.527077 32.59237 ]]
[[35.436085 26.702133]
 [42.539444 33.23772 ]]
[[42.558846 28.304388]
 [44.73082  40.974537]]
[[43.382507 28.347569]
 [50.721615 42.953518]]
[[43.441513 33.352676]
 [58.937195 49.514038]]
